// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq--4t1eJlvVRGq-BK6n4iwqzLqYXSzis',
    appId: '1:366940087617:web:876ada4485b421a10e6dc0',
    messagingSenderId: '366940087617',
    projectId: 'gandalversego',
    authDomain: 'gandalversego.firebaseapp.com',
    storageBucket: 'gandalversego.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0jUm5k2B-B_Mz0xO7B-hgPIjywOYKjBo',
    appId: '1:366940087617:android:b45e24505e3852470e6dc0',
    messagingSenderId: '366940087617',
    projectId: 'gandalversego',
    storageBucket: 'gandalversego.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxdFP2ZTaIbCyIROQRrH1qb5jl-pJAQJE',
    appId: '1:366940087617:ios:419c284abbe7e0da0e6dc0',
    messagingSenderId: '366940087617',
    projectId: 'gandalversego',
    storageBucket: 'gandalversego.appspot.com',
    iosBundleId: 'com.example.gandalverse',
  );
}